//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attnd_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int id { get; set; }
        public Nullable<bool> attendance1 { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> subject_id { get; set; }
        public Nullable<int> teach_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<double> class_time { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Class Class { get; set; }
    }
}
